FROM nginx:alpine

# Nginx konfiguráció másolása
COPY nginx.conf /etc/nginx/nginx.conf

# Frontend fájlok másolása
COPY ../frontend/ /usr/share/nginx/html/

# Port expozálása
EXPOSE 80

# Nginx indítása
CMD ["nginx", "-g", "daemon off;"]
