build_from:
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  amd64: ghcr.io/home-assistant/amd64-base:3.18
  i386: ghcr.io/home-assistant/i386-base:3.18
labels:
  org.opencontainers.image.title: "IntelliVend"
  org.opencontainers.image.description: "Intelligens italautomata rendszer"
  org.opencontainers.image.source: "https://github.com/vinczem/IntelliVend"
  org.opencontainers.image.licenses: "MIT"
args:
  NODEJS_VERSION: "20.11.1-r0"
  BUILD_DATE: "{{ .Date }}"
  VERSION: "1.0.30"
  CACHEBUST: "2024-11-05-13:10"
  CACHEBUST: "{{ .Timestamp }}"
